jdbc.driverClassName=com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
jdbc.url=jdbc:mysql://192.168.0.155:3306/petmillie?useUnicode=true&serverTimezone=UTC
jdbc.username=dk
=======
jdbc.url=jdbc:mysql://localhost:3306/petmillie?useUnicode=true&serverTimezone=UTC
jdbc.username=root
>>>>>>> 906dccf81f3fbb9c4876f42375e8a7d8bcf4a0c5
jdbc.password=1234