jdbc.driverClassName=com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
jdbc.url=jdbc:mysql://192.168.0.155:3306/petmillie?useUnicode=true&serverTimezone=UTC
jdbc.username=dk
=======
jdbc.url=jdbc:mysql://localhost:3306/petmillie?useUnicode=true&serverTimezone=UTC
jdbc.username=root
>>>>>>> 5c2dea6a9cd132817d303bed4e6fe678d710d136
jdbc.password=1234