jdbc.driverClassName=com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
jdbc.url=jdbc:mysql://192.168.0.155:3306/petmillie?useUnicode=true&serverTimezone=UTC
jdbc.username=jia
jdbc.password=1234
=======
<<<<<<< HEAD
jdbc.url=jdbc:mysql://192.168.0.155:3306/petmillie?useUnicode=true&serverTimezone=UTC
jdbc.username=dk
jdbc.password=1234
=======
jdbc.url=jdbc:mysql://localhost:3306/petmillie?useUnicode=true&serverTimezone=UTC
jdbc.username=root
jdbc.password=1234
>>>>>>> c87b59c844cbbbd07fb854a2627b5a302d087cda
>>>>>>> 2a92edae273869112100af055a55e16d6eea765f
